name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'RealEstateFinder/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd RealEstateFinder
          npm ci
      
      - name: Build React app
        run: |
          cd RealEstateFinder
          echo "Current directory: $(pwd)"
          echo "Contents of RealEstateFinder:"
          ls -la
          echo "Contents of client directory:"
          ls -la client/ || echo "Client directory not found"
          echo "Running build command..."
          npm run build:client
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './RealEstateFinder/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
